Flatpak: Update postgresql to 13.23
Fixes the following build error:

    In file included from ../../src/include/postgres_fe.h:25,
                     from config_info.c:20:
    ../../src/include/c.h:317:23: error: ‘bool’ cannot be defined via ‘typedef’
      317 | typedef unsigned char bool;
          |                       ^~~~
    ../../src/include/c.h:317:23: note: ‘bool’ is a keyword with ‘-std=c23’ onwards
    ../../src/include/c.h:317:1: warning: useless type name in empty declaration
      317 | typedef unsigned char bool;
          | ^~~~~~~

Also remove "-Wno-error=incompatible-pointer-types" that no longer
needed thanks to update